language: cpp
compiler: gcc
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8


before_install:
  # grab a pre-built cmake 3.2.3
  - wget --no-check-certificate https://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar xzvf cmake-3.2.3-Linux-x86_64.tar.gz --strip 1 -C $HOME

script:
  # Set compiler to GCC 4.8 here, as Travis overrides the global variables.
  - export CC=gcc-4.8 CXX=g++-4.8
  - cd ./examples
  - "g++-4.8 -std=c++11 example1.cpp -o example"
  - cd ../test
  - mkdir release
  - cd ./release
  - $HOME/bin/cmake ..
  - make

after_script:
  - cd ../test
  - ./system_test_runner.sh
  - cd ./release
  - make test

notifications:
  email: false
