language: cpp
compiler: gcc

before_install:
  # 'python-software-properties' provides add-apt-repository
  - sudo apt-get -y install python-software-properties
  # which is needed to add the ppa that has gcc 4.8
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  # which is needed to install gcc 4.8
  - sudo apt-get -y install gcc-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  # and g++ 4.8
  - sudo apt-get -y install g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

script:
  - cd ./examples
  - "g++ -std=c++11 example1.cpp -o example"

after_script:
  - cd ../test
  - ./system_test_runner.sh

notifications:
  email: false
